### ISSUE TITLE
Mission Selection and Auto Align not working

### ISSUE THREAD

**Issue by flug8** [Matrixchung/EDAutopilot-v2#24]
I did everything to set the script up like it is said in the readme file. The GUI tells me no error. When I start the script with HOME after going in to the passenger lounge, the script begins to click on the three contacts for passenger missions in a loop. It doesn't end, even after 20 minutes. No mission gets selected.

I even tried to start the script at a later point. For example TRUST_UP, when I left the station. Now the script works, until the ship has to align itself. Now the script stops (nothing happens) and crashes after a minute.

What have i done wrong? Does it have to do with recognizing the screen elements, because all other parts are working?

**Comment by flug8** [comment]
![image](https://user-images.githubusercontent.com/80972789/179601588-c5aabca7-098d-40d9-ab5b-fb41036d4b5f.png)
And these two warnings are still showing up, even if I completely clear the inputs

**Comment by Matrixchung** [comment]
> ![image](https://user-images.githubusercontent.com/80972789/179601588-c5aabca7-098d-40d9-ab5b-fb41036d4b5f.png) And these two warnings are still showing up, even if I completely clear the inputs

By default, the Next Panel / Previous Panel keys are the same with rotating map keys ( CamYawRight / CamYawLeft ) which will block the process in Galaxy Map for `setTargetSystem()`.
So about that issue, you need to check the keyboard setting in-game and change the mentioned keybinds to different keys.

**Comment by Matrixchung** [comment]
I have noticed the aligning issues. Currently I am working on a full restructure in the target recognition and alignment part with a completely different algorithm, so I suggest that you can wait a moment for my update to come alive.

**Comment by Matrixchung** [comment]
Plz clone the newest version and try it.
Lots of improvements in basic functions, while Robigo parts still in restructure progress but it will not affect the entire autonomous process.

**Comment by flug8** [comment]
Still this issue. It repeats continuously:
![ezgif-4-5230452c99](https://user-images.githubusercontent.com/80972789/179797080-d3f5c6a1-9dc3-4d64-a48b-a9effa17de5f.gif)

**Comment by Matrixchung** [comment]
Sorry for the unexpected edit.
You might need to backup your original graphics settings and apply [those](https://github.com/Matrixchung/EDAutopilot-v2#useful-settings) especially `GUIColour`.
Note: these settings are temporarily needed since I haven't replace the color templates with grayscale ones. In theory, the grayscale template can be fitted to any of UI color.

**Comment by flug8** [comment]
Thanks, now the recognition works.

Some other thing that are currently a problem:
-  My Python uses the route via WREDGUIA TH-U C16-17 and not C16-18 (fixed it now by myself: I just edited the variable in robigo.py)
-  The auto align isn't really reliable. For about 20% of the time it points a bit too low and the FSD can't be started
-  In most cases. No job is selected, because no mission to sirius is visible, and the bot isn't able to scroll through the missions:
![image](https://user-images.githubusercontent.com/80972789/180280963-e7540ab6-63e4-4ea2-b8f0-16733c69ec38.png)
Anything I can do to fix these issues?

**Comment by Matrixchung** [comment]
* For the alignment issue, maybe you can check `TEMPLATE_CIRCLE_DEAD_ZONE` in `utils/utils.py` and try to lower it, which may improve the accuracy.
* It's surprising that you are faced with so many missions to other destinations :) I will consider adding some scroll to the `get-mission` stage.
